language: generic

env:
  global:
    - ENCRYPTION_LABEL="898853069421"
    - DEPLOY_USER="annevankesteren"

script:
  - curl --remote-name --fail https://resources.whatwg.org/build/deploy.sh && bash ./deploy.sh

notifications:
  email:
    on_success: never
    on_failure: always
