dist: trusty
language: generic

env:
  global:
    - ENCRYPTION_LABEL="898853069421"
    - DEPLOY_USER="annevankesteren"

script:
  - make deploy

notifications:
  email:
    on_success: never
    on_failure: always
