language: generic

env:
  global:
    - ENCRYPTION_LABEL: "898853069421"
addons:
  apt:
    packages:
      - oracle-java8-set-default
install:
  - curl -O https://sideshowbarker.net/nightlies/jar/vnu.jar
script:
  - bash ./deploy.sh
  - /usr/lib/jvm/java-8-oracle/jre/bin/java -jar vnu.jar --skip-non-html /home/travis/build/whatwg/infra
notifications:
  email:
    on_success: never
    on_failure: always
